
##### Environment setup #####

install.packages('devtools')
install.packages('igraph', type = 'binary') # as of 2020/10/06, package "igraph" cannot be installed from source and has to be installed independently from Seurat installation.
install.packages('colorspace')
install.packages('httpuv')
install.packages('fastmap')
install.packages('data.table')
install.packages('htmlwidgets')
install.packages('lazyeval')
install.packages('stringi')
install.packages('hdf5r')
install.packages('Seurat')
install.packages('tidyverse')
install.packages('BiocManager')
install.packages('farver')
install.packages('remotes')
install.packages('ggbeeswarm')
install.packages('R.matlab')
install.packages('pheatmap')
install.packages('ape')
install.packages('clustree')
install.packages('PRROC')
install.packages('WriteXLS')
install.packages('rpart.plot')
install.packages('eulerr')
devtools::install_github("teunbrand/ggh4x")
BiocManager::install('batchelor')
BiocManager::install('DropletUtils')
BiocManager::install('scran')
BiocManager::install('biomaRt')
BiocManager::install('remotes')
BiocManager::install('grimbough/biomaRt') # As of 2020/10/08, there has been a change to Ensembl website. For more details: https://www.biostars.org/p/466100/
BiocManager::install('SingleR')
BiocManager::install('GEOquery')
BiocManager::install("ComplexHeatmap")
BiocManager::install("MAST")
BiocManager::install('kmknn')
BiocManager::install('topGO')
BiocManager::install('org.Mm.eg.db')

# library('Seurat')

sessionInfo()